c2lang/c2compiler

- c2c/Utils/ProcessUtils.cpp
There is an assert here in ProcessUtils, but no #include <assert.h>. C2C won't compile without that line, at least for me
> Quick fix: Missing #include

- INSTALL.md
- README.md
This pull-request adds OS-specific instructions for Arch Linux and fixes some typos. I also rephrased a sentence or two and updated version numbers in README.md
> Arch typos

- c2c/Parser/Sema.cpp
This PR is a fix for #95.
I've just added a quick NULL check before the attributes of the module are printed in Sema::printAST().
> Fix for #95: check for NULL before printing attributes of module

- .gitignore
- bootstrap/Makefile
- bootstrap/bootstrap.c
- bootstrap/external.h
- generator/c2i_generator_stmt.c2
- generator/c_generator.c2
- generator/c_generator_special.c2
- generator/c_generator_stmt.c2
- test/c_generator/stmts/multi_condition_switch.c2t
- test/c_generator/stmts/multi_condition_switch_incr.c2t
- test/c_generator/stmts/switch_stmt.c2t
generator/:
* generate `fallthrough` pseudo-statements instead of `__attribute__((fallthrough))` for portability to compilers that do not support attributes or this particular one.
* generate **external.h** with compiler version detection and select `fallthrough` expansion accordingly
env.sh: define `C2_PLUGINS` as local directory to avoid interfering
with installed c2 version
bootstrap:
* adjust warning flags for older gcc/clang versions
* add extra step in bootstrap/Makefile to generate c2c's build.c using plugins
* update bootstrap/bootstrap.c and bootstrap/external.h (unused?)
* update tests expected C code
> Add support for clang and older gcc compilers

- tools/tester/test_db.c2
- tools/tester/tester.c2
* use 128k buffer instead of 1M to avoid stack overflow
* make `Db.printIssues` return true in case anything is reported
* control verbosity with `-t` (terse) and `-v` (verbose)
* control threads with `-n` (no threads) and `-j` (use treads)
* number of threads can be speficied as optional number after `-j`
* fix code to strip off trailing slash: incorrect for `"/"` and UB for `""`
> Improve tools/tester

- Makefile
- ast_utils/string_pool.c2
- bootstrap/Makefile
- bootstrap/bootstrap.c
- generator/c_generator_special.c2
- parser/c2_tokenizer.c2
- test/parser/utf8-2.c2
* cast `char` index values as `u8` to avoid indexing with negative values on invalid UTF-8 contents
* extend `Identifier_char` and `Char_lookup` arrays to 256 entries
* enable C warning `-Wchar-subscript` (no effect on c2c operation but often an indication of a programming error
* add test for invalid UTF-8 contents in identifier
> Fix undefined behavior on UTF-8 contents

- ast/integer_literal.c2
- parser/c2_parser.c2
- parser/c2_tokenizer.c2
- parser/token.c2
- test/literals/init_int8.c2
- test/literals/invalid_numbers.c2
- tools/tester/issues.c2
- tools/tester/test_db.c2
tester:
output standard error messages
add invalid number tests
add more conversion tests
compiler:
fix `printBinary` output for `0b0`
fix buffer lengths in `printBinary` and `printOctal` add support for hex floats
add missing float syntax
detect invalid syntax for integers and floating point constants detect values beyond 64-bit range for all integer syntaxes
> improve number parser

- parser/c2_tokenizer.c2
- test/literals/invalid_numbers.c2
* fix `hex2val()` for alpha hex digits
* convert integer literals on the fly, no longer use `stdlib.strtoull`
* simplify number parsing, factorize error reporting
* add tests
> lexer: accept _ as digit separator in number literals

- parser/c2_parser_stmt.c2
- test/stmt/for_const.c2
* Allow local definition to start with `const` or `volatile` keyword
* add tests
> parser: fix declaration detection in for initial clause

- ast_utils/string_pool.c2
- compiler/compiler.c2
- compiler/main.c2
- generator/qbe_generator.c2
- parser/parser_utils.c2
- plugins/deps_generator.c2
- tools/c2cat.c2
- tools/c2loc.c2
- tools/c2tags.c2
- tools/common/refs_finder.c2
* make hash size configurable at create time
* Pass hash_table size to `string_pool.Pool.create`
* handle collisions using lists instead of flat arrays, this makes hashing more resilient to pathological collisions
> string_pool: improve hash table handling

- analyser/module_analyser_call.c2
- analyser_utils/printf_utils.c2
- ast/qualtype.c2
- generator/c_generator_expr.c2
- test/attr/printf_integer.c2
- test/attr/printf_ok.c2
- test/attr/printf_prefix.c2
* parse specifier syntax, including * width and/or precision
* check type `i32` for `*` arguments
* accept %b and %B integer conversion specifiers
* accept %e, %g, %a, %E, %F, %G, %A floatingpoint conversion specifiers
* pass extra info tp `FormatHandler`
* fix undefined behavior on incomplete trailing specifier
* more explicit error messages on invalid conversion specifications
* simplify `emitNumberFormat()`
* add tests
> compiler: improve printf format string support

- ast/char_literal.c2
- ast/integer_literal.c2
- parser/ast_builder.c2
- parser/c2_parser.c2
- parser/c2_tokenizer.c2
- parser/token.c2
- tools/c2cat.c2
* use `Radix` enum instead of explicit radix value `None`, `Hex`, `Octal`, `Binary`
> token: use Radix enum for clarity and efficiency

- compiler/compiler.c2
- parser/c2_tokenizer.c2
- parser/token.c2
- tools/c2cat.c2
* fix compilation with `DumpTokens` feature
* extend c2cat to support multiple files
* use a context to avoid global variables
* rename `Feat_invalid` as `Invalid` for invalid character tokens
* produce `Kind.Invalid` tokens for invalid characters in `raw_mode`
* use style names instead of hard-coded colors
> c2cat: prevent lexing errors in raw_mode to allow full module parse

- compiler/c2recipe_parser.c2
- parser/c2_parser.c2
- parser/c2_tokenizer.c2
- parser/token.c2
- tools/c2cat.c2
* use `done` positive end of parse indicator instead of `more`.
* optimize `c2recipe.Token` struct layout
* simplify `Tokenizer.init()`
* initialize `result` token in `lex_internal`. This is more consistent and token was not properly initialized in multiple cases, including lookahead
* pass `result` to `parse_ppexpr()` for `done` flag to be properly updated
> Use Token.done field instead of Token.more

- analyser/module_analyser_switch.c2
- ast/string_literal.c2
- ast_utils/string_buffer.c2
- common/utf8.c2
- generator/c_generator_call.c2
- generator/c_generator_expr.c2
- parser/c2_parser.c2
- parser/c2_parser_expr.c2
- parser/c2_parser_type.c2
- parser/c2_tokenizer.c2
- parser/token.c2
- plugins/git_version_plugin.c2
- plugins/shell_cmd_plugin.c2
- recipe.txt
- test/stmt/switch/switch_case_duplicate_str.c2
- test/stmt/switch/switch_case_embedded_null.c2
- test/stmt/switch/switch_str_case_too_long.c2
- tools/c2cat.c2
* add `Token.name_idx` for clarity
* use `Token.text_idx` only for strings and comments
* `Token.text_len` no longer counts the null terminator, as the name implies
* simplify multi string concatenation.
* accept unicode escape sequences in strings and character constants
* report invalid UTF-8 sequences in strings and character constants
* add `StringLiteral.getTextIndex()`
* add `string_buffer.Buf.encodeBytes()` to encode string fragments with
* add `string_buffer.Buf.add_utf8()` to encode Unicode codepoints in UTF-8 backslash escapes.
* add **utf8** module for encoding and decoding Unicode code points.
* allow up to 255 bytes in string `case` labels
* detect and report duplicate string case labels
* detect and report string case labels `case` with embedded nulls bytes
> compiler: use converted strings from tokenizer

- ast/symbol_table.c2
- ast_utils/string_buffer.c2
- common/diagnostics.c2
- common/string_utils.c2
- common/utf8.c2
- parser/c2_parser.c2
- parser/parser_utils.c2
string_buffer:
* remove `string_buffer.Buf.add_line()`
* add `string_buffer.Buf.vprintf()`
string_utils:
* remove `string_utils.count_tabs()`
* add `string_utils.toLower()`
* fix UB on empty string in `stripNewLine()`
* handle `\r\n` in `stripNewLine()`
* return destination pointer in `toLower()`, `toUpper()`,  `stripNewline()`
utf8:
* add `utf8_sync()` to find character boundaries
parser_utils:
* return offset past the end in `getTokenEnd()`
diagnostics:
* improve range handling
* display line fragment for long lines
* detect and ignore region spanning multiple lines
* handle tabs anywhere on source line
> compiler: improve string_utils and diagnostics output

- analyser/module_analyser_stmt.c2
- analyser/module_analyser_switch.c2
- ast/label_stmt.c2
- ast/stmt.c2
- ast/utils.c2
- generator/ast_visitor.c2
- generator/c/c2i_generator_stmt.c2
- generator/c/c_generator_stmt.c2
- generator/qbe/qbe_generator_stmt.c2
- parser/ast_builder.c2
- parser/c2_parser_stmt.c2
- test/stmt/label_decl.c2
* add `Stmt` pointer in `Label` structure.
* fix grammar for labelled statements and definitions. eg: `if (cond) done: return 0;` is now a single statement.
* accept labelled definitions (generate `label:;`)
* accept labels at end of block (generate `label:;`)
* add tests
> compiler: improve label grammar correctness

- generator/ir/ir_generator_expr.c2
* add dummy block `{}` after label to allow compilation with older clang.
* should rebuilt bootstrap to support labelled declarations.
> syntax: fix compilation error on macOS

- analyser/conversion_checker.c2
- test/expr/bitoffset/bitoffset_invalid_base.c2
- test/expr/bitoffset/bitoffset_invalid_index.c2
- test/init/init_array_designator_ok.c2
- test/init/init_field_designator_ok.c2
- test/literals/init_struct.c2
- test/types/conversion/i8_ptr_to_char_ptr_ok.c2
- test/types/string_init.c2
- test/types/struct_array_init_ok.c2
- test/vars/invalid_init_string.c2
* since `char` is now an alias for `u8`, we no longer accept transparent conversions between `char*` and `i8*`, but we do between `char*` and `u8*`.
* update tests
> analyser: accept conversions between char* and u8*, not i8*

- analyser/module_analyser_unaryop.c2
- parser/c2_parser_expr.c2
* accept unary plus for pointers
* factorise code for unary amp and other unary operators
* accept postfix operators for explicit cast expressions and                                                                                                    
`to_container` expressions
> compiler: fix unary plus for pointers

- analyser/module_analyser_type.c2
- analyser_utils/ctv_analyser.c2
- ast/expr.c2
- ast/unary_operator.c2
- parser/ast_builder.c2
- parser/c2_parser_expr.c2
- test/globals/types/alias_types.c2
- test/types/enum/enum_constant_outofbounds.c2
- test/types/partial/init_char_constlit.c2
- test/types/partial/init_struct_array.c2
* remove `canOverflow()`, only test for `~` operator in `checkRange()`
* factorize code in `Parser.parseCastExpr()`
* add tests
> compiler: simplify unary operator parsing and analysis

- analyser/module_analyser_init.c2
- analyser/module_analyser_unaryop.c2
- ast/array_subscript_expr.c2
- ast/unary_operator.c2
- parser/ast_builder.c2
- parser/c2_parser_expr.c2
- test/init/addr_of_other.c2
- test/types/char_array_string_init_ok.c2
- remove `actOnPostfixUnaryOperator()`
- accept string initializers for `u8[]` and `i8[]`
- make `*expr` an LValue
- fix `&*a` and `&a[b]` ctc status
> Compiler: simplifications, lvalue and ctc fixes

- Makefile
- analyser/module_analyser_builtin.c2
- analyser/module_analyser_call.c2
- analyser/module_analyser_type.c2
- ast/call_expr.c2
- ast/function_decl.c2
- ast/init_list_expr.c2
- ast/instantiator.c2
- ast/type_ref.c2
- ast_utils/context.c2
- bootstrap/Makefile
- common/diagnostics.c2
- common/source_mgr.c2
- parser/ast_builder.c2
- parser/c2_parser_expr.c2
Template function call instantiation:
* fix template function parsing: detect missing argument list, allow call chaining.
* add `instance_ast_idx` in `CallExpr` nodes
* add `instance_ast_idx` in `FunctionDecl` so instantiated template functions have references to both the template and the instantiator module
* add `FunctionDecl.getInstanceModule()` method
* properly detect and accept use of non public or opaque types in template function instances
Other bug fixes:
* add debug target to compile with optimisations disabled
* keep phase 2 bootstrapped executable for debugging
* optionally initialize Context arena block for debugging
* fix bug in `SourceMgr.find_file` causing infinite loop for invalid loc
* detect and report invalid loc in `Diags.internal`
* add missing initializer for …
> Compiler: fix initialization bugs and template function instantiation

- analyser/incr_array_list.c2
- ast/ast.c2
- ast/decl_list.c2
- ast/expr_list.c2
- generator/c/c_generator.c2
- parser/c2_parser.c2
- parser/c2_parser_expr.c2
- parser/c2_parser_stmt.c2
- parser/c2_parser_type.c2
- plugins/unit_test_plugin.c2
* add local stash in `ExprList` and `DeclList` (4 entries)
* allow zero initialization of `ExprList` and `DeclList`
* remove `initial_size` argument to `init` constructor
* this reduces the number of calls to `malloc` and `free` by more than 70%
> Parser: reduce number of malloc calls

- analyser/module_analyser_call.c2
- analyser/module_analyser_function.c2
- ast/compound_stmt.c2
- ast/if_stmt.c2
- ast/member_expr.c2
- ast/while_stmt.c2
- parser/ast_builder.c2
- parser/c2_parser_stmt.c2
- test/stmt/switch/switch_terminating.c2
* use more explicit location computation for missing return in function body
* add `Member.getLastLoc()` for the location of the last member name
* point to function/method name in function call errors
* add actual loc in `IfStmt` and `WhileStmt`
* fix corresponding tests, error should probably point to the case/default clause instead of the last statement and error message would be clearer as 'implicit fallthough is not allowed'
> Compiler: fix some location inconsistencies

- ast_utils/context.c2
* use internal chaining for `Block` lists.
* allow for zero initialization of `Context`.
> Compiler: simplify Context allocator

- Makefile
- ast/call_expr.c2
- common/build_target.c2
- common/string_utils.c2
- compiler/compiler.c2
- compiler/main.c2
- generator/c/c_generator.c2
- generator/c/c_generator_call.c2
- generator/c/c_generator_special.c2
- generator/c/c_generator_trace.c2
- recipe.txt
* add `--trace-calls` command line option
* generate code that counts function and method calls
* selectively output statistics based on `C2TRACE` environment variable
* syntax: C2TRACE="[min=val,][mask=val,][name=]pattern" where:
* min=val specifies the minimum number of calls to output (default=1)
* mask=val specifies what to output (1:functions, 2:calls, 3:both)
* name=pattern is a comma separated list of shell glob expressions to filter the function names to output
> Compiler: add call tracing feature

- parser/c2_tokenizer.c2
- parser/token.c2
- test/parser/invalid_char_96.c2
- test/parser/raw_string.c2t
- test/parser/raw_string_indent_error.c2
- test/parser/raw_string_unterminated.c2
* raw strings are delimited with sequences of backquotes
* raw strings end with a sequence of at least the same length as the initial sequence. Shorter sequences are part of the string.
* backslashes are not interpreted and newlines are accepted
* multi-line raw strings with at least 3 backslashes are parsed as markdown-like blocks: the rest of the line is ignored, each of the following lines must start with at least the same indentation which is not part of the string.
> Syntax: add support for raw strings

- parser/c2_parser.c2
- parser/c2_parser_expr.c2
- parser/c2_parser_stmt.c2
* remove `need_semi` argument in `Parser.parseInitValue()`, `Parser.parseFieldDesignator()` and `Parser.parseArrayDesignator()`
* handle `need_semi` explicitly in `Parser.parseArrayEntry` and `Parser.parseVarDecl()`.
* move `Parser.consumeSemicolon` to c2_parser.c2
> Parser: simplify semicolon handling

- analyser/module_analyser_stmt.c2
- analyser/module_analyser_switch.c2
- analyser/scope.c2
- test/stmt/bad_break.c2
- test/stmt/bad_continue.c2
- test/stmt/bad_fallthrough.c2
* `fallthrough` statement should only be used as the last statement in a `case` statement list except in the final one.
* remove Fallthrough scope flag
* add tests
> Analyser: simplify fallthrough analysis

- generator/c/c_generator.c2
- generator/c/c_generator_special.c2
- libs/libc/csignal.c2i
- libs/libc/sys_socket.c2i
- libs/libc/unistd.c2i
- libs/lua/lua.c2i
- libs/lua/lua_lib.c2i
- test/c_generator/lib_lua.c2t
* use standard types in some function types
* emulate `pipe2` and `accept4` on non Linux targets
* add `accept()` system call
* generate external constant strings as `#define`
* make socket options flags constants, not an enum
> Libraries: fix multiple library issues to compile the examples

- analyser/module_analyser.c2
- analyser/module_analyser_builtin.c2
- ast/builtin_type.c2
- ast/expr.c2
- ast/module.c2
- ast/type_expr.c2
- ast/type_ref.c2
- common/component.c2
- compiler/compiler_libs.c2
- compiler/manifest.c2
- generator/c/c2i_generator_decl.c2
- generator/c/c2i_generator_stmt.c2
- generator/c/c_generator.c2
- generator/c/c_generator_special.c2
- generator/ir/ir_generator.c2
- libs/c2/c2_test.c2i
- libs/c2/manifest.yaml
- test/c_generator/functions/inline/inline_prefix.c2t
- test/interface/incremental_array.c2t
- test/interface/multi_dimension_array.c2t
- test/interface/public_by_array_expr.c2t
- test/vars/array_nosize.c2
* accept array definitions without length in interface files
* reject `elemsof` on arrays of unknown length
* fix external array definitions in C generator
* fix test/interface/incremental_array.c2t: fix external array definition
* fix test/interface/public_by_array_expr.c2t: fix external array definition
* fix test/interface/muti_dimensional_array.c2t: `Row` and `Columns` definitions were reversed, 2D external array definition in C was incorrect
> Fix external array definitions:

- ast/asm_stmt.c2
- ast/builtin_expr.c2
- ast/enum_type_decl.c2
- ast/explicit_cast_expr.c2
- ast/function_decl.c2
- ast/function_type.c2
- ast/init_list_expr.c2
- ast/static_assert.c2
- ast/struct_type_decl.c2
- ast/var_decl.c2
* add missing initialisation in AST nodes
* improve node init order consistency
* simplify expressions
* try and avoid `void*` pointers to ensure type correctness
> Parser: fix missing initializations

- analyser/conversion_checker.c2
- ast/builtin_type.c2
- generator/c/c_generator.c2
- test/types/conversion/integer_types.c2
* use `getBaseType` for conversion checks to convert ISize/USize to 32/64 bit
* fix conversion errors: signed types to smaller unsigned type is loss of integer precision rather than signedness change.
* fix C type generation for isize/usize
> Analyser: fix 32/64 bit issues

- analyser/conversion_checker.c2
- analyser/conversion_checker_expr.c2
- analyser/module_analyser_binop.c2
- analyser/module_analyser_expr.c2
- analyser_utils/ctv_analyser.c2
- ast/builtin_type.c2
- ast/qualtype.c2
- ast/utils.c2
- ast/value.c2
* use standard width 8/16/32/64 for i8/i16/i32/i64
* remove `BuiltinType_bitfield_sizes` and equivalent array in `global`
* remove `BuiltinType.getBitfieldSize()`
* swap `Value.truncate` arguments for consistency
* simplify `Value.getWidth()`, `Value.truncate()` and `Value.castAs()`.
* use single init function `Limit.init()`.
* simplify `Checker.checkIntConversion()`
> Compiler: include sign bit in BuiltinType widths

- ast_utils/string_buffer.c2
- generator/c/c_generator.c2
* add `string-buffer.Buf.trim(len)`
* remove trailing space on attribute line in C output
> Generator: trim attribute output in C generator

- ast_utils/constants.c2
- ast_utils/string_buffer.c2
- common/file/reader.c2
- common/source_mgr.c2
- compiler/compiler.c2
- compiler/compiler_libs.c2
- compiler/main.c2
- tools/c2loc.c2
- add `string_buffer.Buf.detach()` to get buffer with ownership
- add `File.detach()` to get buffer with ownership
- simplify `string_buffer.Buf.newline()`
- add `File.openCount` and `File.is_const`
- unify `File` contents as `File.data_`
- improve CheckPoint system (simpler and much faster)
- remove `Max_open_files`
- remove `close_oldest()`
> SourceMgr: clean API for consistency and flexibility, faster SrcLoc conversion

- ast_utils/string_pool.c2
- common/build_file.c2
- common/source_mgr.c2
- compiler/compiler.c2
- compiler/compiler_libs.c2
- compiler/main.c2
- tools/c2loc.c2
* pass actual strings, let the source manager internalize in the astPool
* remove duplicate filename test
> source-mgr: simplify APIs

- analyser/module_analyser_function.c2
- analyser/module_analyser_type.c2
- ast/type_ref.c2
- generator/c/dep_finder.c2
- parser/c2_parser.c2
- parser/c2_parser_expr.c2
- parser/c2_parser_stmt.c2
- parser/c2_parser_type.c2
- test/builtins/sizeof_ok.c2
- test/expr/sizeof/array.c2
- test/parser/sizeof_addrof.c2
* simplify `Parser.parseTypeSpecifier`: always accept qualifier and arrays
* simplify `Parser.parseSingleTypeSpecifier()`: always accept qualifier
* simplify `Parser.parseOptionalArray()`: always accept arrays, remove base and recursion
* simplify `Parser.parseAsType()`, `Parser.parseAsCastType()`, `Parser.isTemplateFunctionCall()`: remove `has_brackets` handling
* add `isArray()` and `isPointer()` type functions for `TypeRef` and `TypeRefHolder` for clarity and flexibility
* this fixes some problems:
* `sizeof(const char*)` was rejected.
* `a < i32.max` was interpreted as a template function call
* `a < b * c > (d + 1)` was interpreted as a template function call (wrong error)
* `sizeof(Handle[3])` now works for array types
> Parser: simplify type parsing

- parser/c2_parser.c2
- parser/c2_parser_expr.c2
- parser/c2_parser_stmt.c2
- parser/c2_tokenizer.c2
* move token lookahead queue from `Tokenizer` to `Parser`
* add `Parser.peekToken()` and `Parser.peekToken2()` (reads token value)
* better check for unbalanced parentheses and brackets
* produce proper error for bogus expressions in lookahead phases
> Parser: improve token lookahead system

- ir/constant_list.c2
- parser/token.c2
* also remove redundant `(void*)` cast
> Compiler: remove last cpp style cast
